### PR TITLE
Create ar.json

### PR DESCRIPTION
**Pull request by Mona1988**

### CODE REVIEW

**Comment by ffoodd** [comment]
Hi there,

I'd be glad to help you contribute to this project, if you need :)

**Comment by Mona1988** [comment]
Hi all,

Yes please. I would  like to contribute to this project. I would like to
translate this tool  to Arabic. Can anybody help me translate this tool
step by step.

Thank you,
Mona

**Comment by ffoodd** [comment]
I see in this PR (based on your `patch-1` branch) that you created `ar.json`. To make this simpler to you, I suggest you only edit this file (and I'll finish the process right after merging).

So in order to translate a11y.css to Arabic, the simplest way is:
* to copy everything in `en.json` in your `ar.json` file;
* for each line, translate the second text entry (eg. the first line in `en.json` is `"ui:error": "Errors"`; you only have to translate `Errors`).

Do you think you'll be able to do this?

**Comment by Mona1988** [comment]
sure! I will do that right now.

**Comment by Mona1988** [comment]
Done translating the file!

**Comment by ffoodd** [comment]
Well done!

I'll merge it right away, end the translation process and will ask you to review the Arabic version :)

Thanks a lot!

**Comment by ffoodd** [comment]
Hi,

I just ended the translation process. Since I'm not an Arabic speaker, may tou check a few things?

- [ ] In [the documentation website](http://ffoodd.github.io/a11y.css/index.html), I added Arabic to the language selector in the bookmarklet generator: I used `dir="trl"` on the `<option>` tag, is that correct?
- [ ] Should I also switch direction in CSS displayed messages (using [direction](https://developer.mozilla.org/fr/docs/Web/CSS/direction))? If so, that'll need a little more work :)

Thanks a lot for contributing!

**Comment by nico3333fr** [comment]
Hi there,

1) this is correct imho.

2) if the `dir=rtl` is set up on content, no need to add `direction` property. As you're using CSS-generated content (with LTR/RTL mixed content), to be honest, I never encountered this case.

My (tiny) experience: most of the time, it is better to let the browser do the job as you did. 

However, I'm interested in informations you could get on this ;)

**Comment by Mona1988** [comment]
Sure. Thank you.

**Comment by Mona1988** [comment]
Hi all,

How can I start using only the Arabic version of the tool. Can I download
only the Arabic version of the tool?

Mona

**Comment by ffoodd** [comment]
You have multiple ways:
* the simpler is to create a new bookmark in your browser, with `javascript:(function(){a11ycss=document.createElement("LINK");a11ycss.href="https://rawgit.com/ffoodd/a11y.css/master/css/a11y-ar.css";a11ycss.rel="stylesheet";a11ycss.media="(min-width:%20800px)";document.body.appendChild(a11ycss);})();` as URL;
* another way is to directly download [this file](https://raw.githubusercontent.com/ffoodd/a11y.css/master/css/a11y-ar.css) and use it wherever you want by adding it as any other CSS file.

I think these are the two best ways to use it.

Is that enough for you to use it, or do you need other suggestions?

**Comment by Mona1988** [comment]
I was able to create a bookmark. I notice some problems with this tool,
which sometimes doesn't give you the number of errors, warnings, advice,
and absolute with some  websites.

**Comment by ffoodd** [comment]
There's a list of known issues in the wiki.

As far as I can see with waht you describe:
* either those websites have some active CSP, preventing a11y.css to apply;
* or, as a11y.css is *only CSS*, some styles on the websites are overriding a11y.css' ones.

Moreover there are many limitations due to CSS: some tags don't support pseudo-elements, or the same tag may trigger multiple messages.

If you need a more robust and reliable tool, I suggest you use the excellent [aXe](https://www.deque.com/products/axe/), which is available as browser extension.

**Comment by Mona1988** [comment]
Thank you so much for the explanation. Is aXe availabile in Arabic?

**Comment by ffoodd** [comment]
I don't think so, from what I know they started to work on internationalization a few months ago. I don't think there is any stable release including other languages than English for now.

**Comment by Mona1988** [comment]
I see. Thank you so much. I’m trying to do an accessibility tool as my
advisor requested and I know a little about http and php, and I really want
a guide or a book can help me step by step developing this tool. It doesn’t
have to be perfect, a prototype is ok. I appreciate if you guys can provide
me with resources or advice to let me get started. Thank you in advance.

**Comment by ffoodd** [comment]
Wow, this is really a big thing. I recommend you build on top of aXe tests: accessibility testing is very hard and aXe offers the better automated tests suite, alongwith Tenon.io.

I seriously suggest you consqider not creating a tool but contribute to an existing project, as aXe or Tenon: you won't do better by yourself. Those tools have been around for years, and their creators are dedicated to accessibility for decades now. 

Just use them, and if they don't have an Arabic translation for now, try to help them :)

**Comment by Mona1988** [comment]
You scared me Looool.  My advisor doesn't want me to do a better one. He
just want me to develop an accessibility tool that can give errors and
solutions in Arabic. He said it doesn't have to be perfect.  A prototype is
fine with him.
He gave me a few months to develop it, but he wants to see that I start
something in 3 weeks. Do you think I can do that ?

**Comment by ffoodd** [comment]
You may try but I seriously recommend you try to use aXe or Tenon: you may integrate it in your own tool if you wan (translating, working on UX/UI, etc.) but developping test needs a very consistent technical background.

**Comment by Mona1988** [comment]
Thanks for the suggestions!

**Pull request merged**
