### PR TITLE
File Creation pt-br.json

### PR DESCRIPTION
**Pull request by bruno-machado**
Translated into Portuguese

### CODE REVIEW

**Comment by ffoodd** [comment]
Hi there :)

Some strings still are in english, should I wait until they're translated before merging?

Thanks a lot for your work!

**Comment by bruno-machado** [comment]
Hi there.
I made a mistake, I already changed the fields. But some will be in English.

you are welcome

**Comment by ffoodd** [comment]
Are you OK to merge it right now, or do you plan to translate some other strings before?
To me it's awesome already :)

**Comment by bruno-machado** [comment]
Yes, I can translate others in the future

**Comment by bruno-machado** [comment]
erro?

**Pull request closed without merging**
