### PR TITLE
update URL to WAI-ARIA links and other

### PR DESCRIPTION
**Pull request by zwiastunsw**
update URL to WAI-ARIA, accede-web.com, punkchip.com, jkorpela.fi
delete URL to https://webino.se/security/..., https://michaelthelin.se/... (non exist)

### CODE REVIEW

**Comment by zwiastunsw** [comment]
Is there a problem with merging?

**Comment by ffoodd** [comment]
Well, I'm a human being with a life, not always up to click on a button :)

**Comment by zwiastunsw** [comment]
I understand, that's why I reminded myself  :)

**Comment by zwiastunsw** [comment]
thx

**Pull request merged**
