### PR TITLE
Add package-lock.json

### PR DESCRIPTION
**Pull request by GeorgeGkas**
From version 5 of npm, a default package-lock.json is generated to ensure a consistent install and compatible dependencies. This file has to be included in source control as it is proposed by the documentation of npm.

### CODE REVIEW

**Comment by ffoodd** [comment]
Hi there, thanks for the PR!

I already tried adding it, and had to remove it multiple times since npm 5 isn't stable AT ALL.

One of (many) encountered drawbacks is that it crashed Travis build, so I think if this PR passes Travis' checks, I'll merge it :)

Wait and see!

**Comment by GeorgeGkas** [comment]
@ffoodd This is not necessarily a problem with npm. This problem might be encountered due to false `.yml` configuration or unstable nodejs version. Right now the build is pending. I would like to see if it will fail or not and we can try an alternative config for travis. What do you think?

**Comment by ffoodd** [comment]
It's a good idea, everything that can improve this project is welcome :)
For now Travis uses node 7, which is not the current nor the latest LTS so we probably could try to upgrade it.

When I tried to use npm 5 + `package-lock.json` there were so much issues everywhere that I didn't want to wait. Maybe all of this is fixed now. Let's see!

**Comment by GeorgeGkas** [comment]
Let me close this PR and come back later with a fix.

**Comment by ffoodd** [comment]
Please reopen it, build passed: https://travis-ci.org/ffoodd/a11y.css/builds/329776076

Travis platform had troubles, jobs were just pending for a long time :)

And in fact reading the build process, npm with node 7 was in version 4, so not using npm 5 package-lock.json.

We might try to upgrade node and npm in Travis configuration. 

Please let me know if you wanna try; if not I'll open a dedicated issue and try this by myself later: )

**Pull request closed without merging**
