### PR TITLE
Added Spanish language

### PR DESCRIPTION
**Pull request by Dionakra**
Added translation to Spanish language by following [wiki steps](https://github.com/ffoodd/a11y.css/wiki/Translations)

### CODE REVIEW

**Comment by Dionakra** [comment]
TravisCI NodeJS version has been upgraded to version 10, as it was generating some problems (see [build #574](https://travis-ci.org/github/ffoodd/a11y.css/builds/753004315) and [build #575](https://travis-ci.org/github/ffoodd/a11y.css/builds/753009108))

**Comment by ffoodd** [comment]
Thanks a lot @Dionakra, this is perfect (and awesome :heart_eyes:).

I'll try to publish a new release soon to make this available :)

**Comment by ffoodd** [comment]
@Dionakra May I suggest you also give a shot at localizing the webextension? There's also [a dedicated wiki page](https://github.com/ffoodd/a11y.css/wiki/Localization). And if not, I'll try by myself :)

**Comment by Dionakra** [comment]
@ffoodd sure, will do today :)

**Pull request merged**
