### PR TITLE
Webextension for chrome

### PR DESCRIPTION
**Pull request by Wolf-Legend**
All files are same as webextension  for  mozilla only manifest file is changed  to work for chrome.

### CODE REVIEW

**Comment by Wolf-Legend** [comment]
Its not related to other files the change is just in manifest file but since both browser uses different manifest file. But we cant keep two files with same name(manifest) so i used different folder.

**Comment by notabene** [comment]
@ffoodd Your magical gulp skillz ;) could perhaps have a `manifest.firefox.json` and a `manifest.chrome.json` in the original folder, and then push one to an `output/chrome` and the other to `output/firefox` when we package, what do you think?

**Comment by notabene** [comment]
@ffoodd :
> @notabene Would it be the only issue concerning Chrome's webextension?

No, the main difference resides in Promises (for modern browsers) versus callbacks (for Chrome). I can't wrap my head around it.

**Comment by Wolf-Legend** [comment]
@ffoodd  yes the only difference between both manifests is the removal of application key.
I tried both bookmarklet and the extension on chrome and both are giving the same results.
bookmarklet
extension

**Comment by ffoodd** [comment]
Duplicated by #324

**Pull request closed without merging**
